### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by mjenczmyk**
Apart of fixing compilation errors chords should no longer be displayed in italics. In future (or even in this pull request if you want it) we may add the command similar to the one below to make typing chords easier.

```
\newcommand{\foo}{$\mathrm{#1^{#2}_{#3}$}
```

### CODE REVIEW

**Comment by mjenczmyk** [comment]
What's most important - check if compiles without ignoring any errors and whether chords aren't written with italics in compiled songbook.

**Review by qamil95 — COMMENTED** [review]
Succesfully compiled and no italics, but I dislike syntax of .tex files now - they looks totally not userfriendly, and generally I want to keep these files possible to be modified by non-technical people. Can this $\mathrm{xxx}$ be added in some pre-compile script, allowing us to keep files in repo unchanged? I'm sure that you have not modified them manually, so this script already exists ;)

**Comment by mjenczmyk** [comment]
> Can this $\mathrm{xxx}$ be added in some pre-compile script, allowing us to keep files in repo unchanged? I'm sure that you have not modified them manually, so this script already exists ;)

Actually I did it with a regex expression. I cannot make it so this `$\mathrm{}$` wrapper is added at the compilation (maybe somebody can), but I can add command `\chord` that would map chords like below.

```
\chord{C} -> $\mathrm{C}$
\chord{C}{7} -> $\mathrm{C^7}$
\chord{C}{7}{4} -> $\mathrm{C_4^7}$
```

**Comment by qamil95** [comment]
I vote for not merging these changes, keep current version of songs in repo, but use regex mentioned by you after creating list of songs and before compiling. My idea is that https://github.com/qamil95/SonglistGenerator will be used to create master.tex file, which would be used to compile, so we can also call regex with mathrm at this stage (and create master.tex with songs, too).

**Comment by mjenczmyk** [comment]
OK, I'll try to write the expression I've used once more time (I'm pretty sure I haven't saved it) - but note that it didn't solve all the issues at once and I had to apply manual changes further. I'm not so sure I'm able to write such regexp that will make such automation possible (I'm not a fan of such idea anyway), but maybe after adjusting it it'll be possible.

**Comment by qamil95** [comment]
If it comes to manual changes after running regexp - I hope that it would be better to unify .tex files if they are written in weird way instead of making script more complicated.
There should be only two form of chords allowed**: F^7 for one char after ^, and F^{7+} for two or more characters.**
If there are missing spaces in songs, they should be fixed manually in song file.
If there is chord f#, it should be changed to fis.
If chords are using different syntax for chords, it should be also fixed.

**Comment by qamil95** [comment]
Now we have github workflow, that runs SonglistGenerator. It creates zip archive with all files required to build spiewnik, so we should apply something adding mathrm where needed just before running songlist generator, but after checking out repository. As a result, we will get user friendly .tex files in repo, but latex-friendly ones as output.

**Comment by qamil95** [comment]
And now it works as described in my last comment, so closing this PR.

**Pull request closed without merging**
